### ISSUE TITLE
Robotics work shops R &  D

### ISSUE THREAD

**Issue by dnkr10** [vijayellenti/IR#44]
**Urls**
- http://www.roboversity.com/

- http://robotechlabs.com/workshops/

- http://robotechlabs.com/workshops/
- http://www.i3indyatechnologies.com/workshop/robotics-workshops.html
- http://www.skyfilabs.com/robotics-courses-and-workshops
- http://www.arktechnosolutions.com/courses-robotics.aspx
- http://robox.in/enquiry.html?gclid=CjwKEAjw9MrIBRCr2LPek5-h8U0SJAD3jfht0nqsShwtXtyy5soR-
    jJCFFCG5Tqtqd9x2OEXJYIC6xoCW_fw_wcB
- https://www.slideshare.net/pratikdhaboo/basic-robotics-workshop
- https://www.slideshare.net/avikdhupar/robotics-workshop-ppt
- http://www.powershow.com/view1/1ace84-
   ZDc1Z/ROBOTICS_WORKSHOP_powerpoint_ppt_presentation

**Comment by vijayellenti** [comment]
created another ticket
